/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PekosRouteImport } from './routes/pekos'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SeedsIndexRouteImport } from './routes/seeds/index'
import { Route as TemplatesSplatRouteImport } from './routes/templates_.$'
import { Route as SeedsSplatRouteImport } from './routes/seeds/$'
import { Route as BundlesSplatRouteImport } from './routes/bundles_.$'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as PekoOwnerPekoNameRouteImport } from './routes/peko.$owner.$pekoName'
import { Route as POwnerPrincipalNameRouteImport } from './routes/p.$owner.$principalName'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PekosRoute = PekosRouteImport.update({
  id: '/pekos',
  path: '/pekos',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeedsIndexRoute = SeedsIndexRouteImport.update({
  id: '/seeds/',
  path: '/seeds/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesSplatRoute = TemplatesSplatRouteImport.update({
  id: '/templates_/$',
  path: '/templates/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SeedsSplatRoute = SeedsSplatRouteImport.update({
  id: '/seeds/$',
  path: '/seeds/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BundlesSplatRoute = BundlesSplatRouteImport.update({
  id: '/bundles_/$',
  path: '/bundles/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const PekoOwnerPekoNameRoute = PekoOwnerPekoNameRouteImport.update({
  id: '/peko/$owner/$pekoName',
  path: '/peko/$owner/$pekoName',
  getParentRoute: () => rootRouteImport,
} as any)
const POwnerPrincipalNameRoute = POwnerPrincipalNameRouteImport.update({
  id: '/p/$owner/$principalName',
  path: '/p/$owner/$principalName',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/pekos': typeof PekosRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/bundles/$': typeof BundlesSplatRoute
  '/seeds/$': typeof SeedsSplatRoute
  '/templates/$': typeof TemplatesSplatRoute
  '/seeds/': typeof SeedsIndexRoute
  '/p/$owner/$principalName': typeof POwnerPrincipalNameRoute
  '/peko/$owner/$pekoName': typeof PekoOwnerPekoNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/pekos': typeof PekosRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/bundles/$': typeof BundlesSplatRoute
  '/seeds/$': typeof SeedsSplatRoute
  '/templates/$': typeof TemplatesSplatRoute
  '/seeds': typeof SeedsIndexRoute
  '/p/$owner/$principalName': typeof POwnerPrincipalNameRoute
  '/peko/$owner/$pekoName': typeof PekoOwnerPekoNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/pekos': typeof PekosRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/bundles_/$': typeof BundlesSplatRoute
  '/seeds/$': typeof SeedsSplatRoute
  '/templates_/$': typeof TemplatesSplatRoute
  '/seeds/': typeof SeedsIndexRoute
  '/p/$owner/$principalName': typeof POwnerPrincipalNameRoute
  '/peko/$owner/$pekoName': typeof PekoOwnerPekoNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/discover'
    | '/pekos'
    | '/profile'
    | '/search'
    | '/auth/callback'
    | '/bundles/$'
    | '/seeds/$'
    | '/templates/$'
    | '/seeds/'
    | '/p/$owner/$principalName'
    | '/peko/$owner/$pekoName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/discover'
    | '/pekos'
    | '/profile'
    | '/search'
    | '/auth/callback'
    | '/bundles/$'
    | '/seeds/$'
    | '/templates/$'
    | '/seeds'
    | '/p/$owner/$principalName'
    | '/peko/$owner/$pekoName'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/discover'
    | '/pekos'
    | '/profile'
    | '/search'
    | '/auth/callback'
    | '/bundles_/$'
    | '/seeds/$'
    | '/templates_/$'
    | '/seeds/'
    | '/p/$owner/$principalName'
    | '/peko/$owner/$pekoName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DiscoverRoute: typeof DiscoverRoute
  PekosRoute: typeof PekosRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  BundlesSplatRoute: typeof BundlesSplatRoute
  SeedsSplatRoute: typeof SeedsSplatRoute
  TemplatesSplatRoute: typeof TemplatesSplatRoute
  SeedsIndexRoute: typeof SeedsIndexRoute
  POwnerPrincipalNameRoute: typeof POwnerPrincipalNameRoute
  PekoOwnerPekoNameRoute: typeof PekoOwnerPekoNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pekos': {
      id: '/pekos'
      path: '/pekos'
      fullPath: '/pekos'
      preLoaderRoute: typeof PekosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seeds/': {
      id: '/seeds/'
      path: '/seeds'
      fullPath: '/seeds/'
      preLoaderRoute: typeof SeedsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates_/$': {
      id: '/templates_/$'
      path: '/templates/$'
      fullPath: '/templates/$'
      preLoaderRoute: typeof TemplatesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seeds/$': {
      id: '/seeds/$'
      path: '/seeds/$'
      fullPath: '/seeds/$'
      preLoaderRoute: typeof SeedsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundles_/$': {
      id: '/bundles_/$'
      path: '/bundles/$'
      fullPath: '/bundles/$'
      preLoaderRoute: typeof BundlesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peko/$owner/$pekoName': {
      id: '/peko/$owner/$pekoName'
      path: '/peko/$owner/$pekoName'
      fullPath: '/peko/$owner/$pekoName'
      preLoaderRoute: typeof PekoOwnerPekoNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$owner/$principalName': {
      id: '/p/$owner/$principalName'
      path: '/p/$owner/$principalName'
      fullPath: '/p/$owner/$principalName'
      preLoaderRoute: typeof POwnerPrincipalNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DiscoverRoute: DiscoverRoute,
  PekosRoute: PekosRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  BundlesSplatRoute: BundlesSplatRoute,
  SeedsSplatRoute: SeedsSplatRoute,
  TemplatesSplatRoute: TemplatesSplatRoute,
  SeedsIndexRoute: SeedsIndexRoute,
  POwnerPrincipalNameRoute: POwnerPrincipalNameRoute,
  PekoOwnerPekoNameRoute: PekoOwnerPekoNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
